version: "3.11"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
  redis:
    image: redis:alpine
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A core worker -l INFO
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
volumes:
  static_volume:
  media_volume:
